<?php
// $Id$


function fedora_image_blocks_block($op = 'list', $delta = 0, $edit = array()) {
  // The $op parameter determines what piece of information is being requested.
  switch ($op) {
    case 'list':
      // If $op is "list", we just need to return a list of block descriptions.
      // This is used to provide a list of possible blocks to the administrator,
      // end users will not see these descriptions.
      $blocks[0] = array(
        'info' => t('Image Rotator Block'),
      );
      $blocks[1] = array(
          'info' => t('Whats New Block'),
      );

      return $blocks;
    case 'configure':
      // If $op is "configure", we need to provide the administrator with a
      // configuration form. The $delta parameter tells us which block is being
      // configured. In this example, we'll allow the administrator to customize
      // the text of the first block.
              // If $op is "configure", we need to provide the administrator with a
      // configuration form. The $delta parameter tells us which block is being
      // configured. In this example, we'll allow the administrator to customize
      // the text of the first block.
      $form = array();
      switch ($delta) {
        case 0:
          // This is the image rotator block.
          $form['fedora_image_rotator_block_query'] = array(
            '#type' => 'textarea',
            '#title' => t('ITQL Query'),
            '#description' => t('The ITQL query to return a list of images.'),
            '#default_value' => variable_get('fedora_image_rotator_tagger_block_query', 'select $object $title from <#ri>
where $object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/ilives:figures>
and $object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
and $object <dc:title> $title'),
          );

	  $form['fedora_image_rotator_block_query'] = array(
			'#type'=>'textarea',
			'#title' => t('Image Rotator Collection Query'),
			'#description' => t('The collection to pull random images from for the rotator block.'),
		  '#default_value' => variable_get('fedora_image_rotator_block_query','select $object $title $collection $collectionTitle from <#ri>
where $object <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> <info:fedora/ilives:figures>
and <info:fedora/ilives:figures> <dc:identifier> $collection
and <info:fedora/ilives:figures> <dc:title> $collectionTitle
and $object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
and $object <dc:title> $title'),
	  );



	 $form['fedora_image_rotator_block_numimages'] = array(
            '#type'=>'textfield',
            '#title' => t('The number of images to display in the block.'),
            '#default_value' => variable_get('fedora_image_rotator_block_numimages',1));

    $form['fedora_image_blocks_cache_time'] = array(
            '#type'=>'textfield',
            '#title' => t('The number seconds to cache the images and query results.'),
            '#default_value' => variable_get('fedora_image_blocks_cache_time',3600));


          break;

  
          case 1:
          // All we need to provide is a text field, Drupal will take care of
          // the other block configuration options and the save button.
         $form['fedora_whats_new_block_title'] = array(
            '#type' => 'textfield',
            '#title' => t('Title'),
            '#size' => 15,
            '#description' => t('The title of the block'),
            '#default_value' => variable_get('fedora_whats_new_block_title', t('Title')),
          );
          break;	  
      }

      return $form;
    case 'save':
      // If $op is "save", we need to save settings from the configuration form.
      // Since the first block is the only one that allows configuration, we
      // need to check $delta to make sure we only save it.
      switch ($delta) {
        case 0:
	variable_set('fedora_image_rotator_block_query', $edit['fedora_image_rotator_block_query']);
// 	variable_set('fedora_image_rotator_block_collection', $edit['fedora_image_rotator_block_collection']);
	variable_set('fedora_image_rotator_block_numimages', $edit['fedora_image_rotator_block_numimages']);
	variable_set('fedora_image_blocks_cache_time', $edit['fedora_image_blocks_cache_time']);
	break;
        
	case 1:
	// Have Drupal save the string to the database.
	variable_set('fedora_whats_new_block_title', $edit['fedora_simple_book_search_block_title']);
	break;	  
      }
      return;
    case 'view': default:
      // If $op is "view", then we need to generate the block for display
      // purposes. The $delta parameter tells us which block is being requested.
      switch ($delta) {
        case 0:
          module_load_include('inc', 'fedora_image_blocks', 'image_rotator_block');
          $block['subject'] = t('Random repository image');
          $block['content'] = _fedora_image_rotator_block_content();
          break;

	case 1:
          module_load_include('inc', 'fedora_image_blocks', 'whats_new_block');
	  $block['subject'] = t('What\'s New');
          $block['content'] = whats_new_block();
          break;	  
      }

      return $block;
  }
}



